version: 2.1

aliases:
  - &defaults
    resource_class: small
    docker:
      - image: cimg/node:lts
  - &save-cache-yarn
    key: yarn-packages-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn
  - &restore-cache-yarn
    name: Restore Yarn Package Cache
    keys:
      - yarn-packages-{{ checksum "yarn.lock" }}

commands:
  persist-workspace:
    steps:
      - persist_to_workspace:
          root: ~/
          paths:
            - project
  attach-workspace:
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn install

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-yarn
      - run:
          name: Yarn version
          command: yarn -v
      - run:
          name: Yarn Install
          command: |
            yarn install --frozen-lockfile --no-progress --non-interactive --cache-folder ~/.cache/yarn
      - save_cache: *save-cache-yarn
      - persist-workspace
  lint:
    <<: *defaults
    steps:
      - attach-workspace
      - run:
          name: Lint
          command: yarn lint
  validate-schema:
    <<: *defaults
    steps:
      - attach-workspace
      - run:
          name: Validate Schema
          command: yarn validate:schema
  test:
    <<: *defaults
    steps:
      - attach-workspace
      - run:
          name: Run Jest
          command: yarn test
  format-check:
    <<: *defaults
    steps:
      - attach-workspace
      - run:
          name: Format Check
          command: yarn format:check
  validate-examples:
    <<: *defaults
    steps:
      - attach-workspace
      - run:
          name: Run TSC
          command: yarn validate:examples
  build:
    <<: *defaults
    steps:
      - attach-workspace
      - run:
          name: Build
          command: yarn build

workflows:
  tests:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - validate-schema:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - validate-examples:
          requires:
            - checkout
      - format-check:
          requires:
            - checkout
      - build:
          requires:
            - checkout
